name: Deploy
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
